=== re-motion/Framework-Archive/Data/DomainObjects/storageProviders.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
		xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		xmlns:sp="http://www.rubicon-it.com/Data/DomainObjects/Persistence/1.0"
		xmlns:t="http://www.rubicon-it.com/Data/DomainObjects/Types"
		elementFormDefault="qualified" 
		attributeFormDefault="unqualified"
		targetNamespace="http://www.rubicon-it.com/Data/DomainObjects/Persistence/1.0">
		
	<xs:import namespace="http://www.rubicon-it.com/Data/DomainObjects/Types" schemaLocation="types.xsd" />
		
	<xs:element name="storageProviders">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="storageProvider" type="sp:storageProviderType" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="application" type="t:requiredStringType" use="required" />
		</xs:complexType>
		
		<xs:key name="storageProviderKey">
			<xs:selector xpath="sp:storageProvider" />
			<xs:field xpath="@id" />
		</xs:key>
	</xs:element>
	
	<xs:complexType name="storageProviderType">
		<xs:sequence>
			<xs:element name="type" type="t:dotNetType" />
			<xs:element name="configuration">
				<xs:complexType>
					<xs:sequence>
						<xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax" namespace="##other" /> 
					</xs:sequence>
					<xs:attribute name="type" type="t:dotNetType" use="required" />	
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="t:requiredStringType" use="required" />
	</xs:complexType>
	
</xs:schema>

=== re-motion/Framework-Archive/Data/DomainObjects.UnitTests/storageProvidersWithSchemaException.xml
<?xml version="1.0" encoding="UTF-8"?>
<storageProviders 
		application="UnitTests" 
		xmlns="http://www.rubicon-it.com/Data/DomainObjects/Persistence/1.0" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Persistence/1.0 ..\storageProviders.xsd">
		
	<storageProvider id="TestDomain">
	  <!-- Unspecified type generates a StorageProviderConfigurationException when file is loaded. -->
		<type></type>
		<configuration type="Rubicon.Data.DomainObjects.Persistence.Rdbms.RdbmsProviderDefinition, Rubicon.Data.DomainObjects">
			<connectionString xmlns="http://www.rubicon-it.com/Data/DomainObjects/Persistence/Rdbms">Integrated Security=SSPI;Initial Catalog=TestDomain;Data Source=localhost</connectionString>		
		</configuration>
	</storageProvider>
	<storageProvider id="UnitTestStorageProviderStub">
		<type>Rubicon.Data.DomainObjects.UnitTests.UnitTestStorageProviderStub, Rubicon.Data.DomainObjects.UnitTests</type>
		<configuration type="Rubicon.Data.DomainObjects.UnitTests.UnitTestStorageProviderStubDefinition, Rubicon.Data.DomainObjects.UnitTests" />
	</storageProvider>

</storageProviders>

=== re-motion/Framework-Archive/Data/DomainObjects.CodeGenerator.UnitTests/storageProviders.xml
<?xml version="1.0" encoding="UTF-8"?>
<storageProviders 
		application="UnitTests" 
		xmlns="http://www.rubicon-it.com/Data/DomainObjects/Persistence/1.0" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Persistence/1.0 ..\DomainObjects\storageProviders.xsd">
		
	<storageProvider id="FirstStorageProvider">
		<type>Rubicon.Data.DomainObjects.Persistence.Rdbms.SqlProvider, Rubicon.Data.DomainObjects</type>
		<configuration type="Rubicon.Data.DomainObjects.Persistence.Rdbms.RdbmsProviderDefinition, Rubicon.Data.DomainObjects">
			<connectionString xmlns="http://www.rubicon-it.com/Data/DomainObjects/Persistence/Rdbms">Integrated Security=SSPI;Initial Catalog=CodeGeneratorUnitTests1;Data Source=localhost</connectionString>		
		</configuration>
	</storageProvider>
	<storageProvider id="SecondStorageProvider">
    <type>Rubicon.Data.DomainObjects.Persistence.Rdbms.SqlProvider, Rubicon.Data.DomainObjects</type>
    <configuration type="Rubicon.Data.DomainObjects.Persistence.Rdbms.RdbmsProviderDefinition, Rubicon.Data.DomainObjects">
      <connectionString xmlns="http://www.rubicon-it.com/Data/DomainObjects/Persistence/Rdbms">Integrated Security=SSPI;Initial Catalog=CodeGeneratorUnitTests2;Data Source=localhost</connectionString>
    </configuration>
  </storageProvider>
  <storageProvider id="NonRdbmsStorageProvider">
    <type>Rubicon.Data.DomainObjects.CodeGenerator.UnitTests.NonRdbmsStorageProvider, Rubicon.Data.DomainObjects.CodeGenerator.UnitTests</type>
    <configuration type="Rubicon.Data.DomainObjects.CodeGenerator.UnitTests.NonRdbmsStorageProviderDefinition, Rubicon.Data.DomainObjects.CodeGenerator.UnitTests" />
  </storageProvider>

</storageProviders>
