=== re-motion/Framework-Archive/Data/DomainObjects.Web.Test/bin/mapping.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:m="http://www.rubicon-it.com/Data/DomainObjects/Mapping" xmlns:t="http://www.rubicon-it.com/Data/DomainObjects/Types" elementFormDefault="qualified" attributeFormDefault="unqualified" targetNamespace="http://www.rubicon-it.com/Data/DomainObjects/Mapping" xml:lang="en">

  <xs:import namespace="http://www.rubicon-it.com/Data/DomainObjects/Types" schemaLocation="types.xsd" />

  <xs:element name="mapping">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="classes" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="class" type="m:classType" maxOccurs="unbounded">

                <xs:key name="propertyKey">
                  <xs:selector xpath="m:properties/m:property" />
                  <xs:field xpath="@name" />
                </xs:key>

              </xs:element>
            </xs:sequence>
          </xs:complexType>

        </xs:element>
        <xs:element name="relations" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="relation" type="m:relationType" maxOccurs="unbounded" />
            </xs:sequence>
          </xs:complexType>

          <xs:key name="relationKey">
            <xs:selector xpath="m:relation" />
            <xs:field xpath="@id" />
          </xs:key>

          <xs:key name="relationClassPropertyKey">
            <xs:selector xpath="m:relation/m:*" />
            <xs:field xpath="m:class/@id" />
            <xs:field xpath="m:property/@name" />
          </xs:key>

        </xs:element>
      </xs:sequence>
      <xs:attribute name="application" type="t:requiredStringType" use="required" />
    </xs:complexType>

    <xs:key name="classKey">
      <xs:selector xpath="m:classes/m:class" />
      <xs:field xpath="@id" />
    </xs:key>

    <xs:keyref name="endPointToClass" refer="m:classKey">
      <xs:selector xpath="m:relations/m:relation/m:*" />
      <xs:field xpath="m:class/@id" />
    </xs:keyref>

  </xs:element>

  <xs:complexType name="classType">
    <xs:sequence>
      <xs:element name="type" type="t:dotNetType" />
      <xs:element name="entity" type="t:requiredStringType" />
      <xs:element name="storageProviderID" type="t:requiredStringType" />
      <xs:element name="properties">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="property" type="m:propertyType" minOccurs="0" maxOccurs="unbounded" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="t:requiredStringType" use="required" />
    <xs:attribute name="baseClass" type="t:requiredStringType" use="optional" />
  </xs:complexType>

  <xs:complexType name="propertyType">
    <xs:sequence>
      <xs:element name="type" type="m:simpleTypeOrDotNetType" />
      <xs:element name="column" type="t:requiredStringType" />
      <xs:element name="nullable" type="xs:boolean" minOccurs="0" />
      <xs:element name="maxLength" type="m:positiveIntType" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="name" type="t:requiredStringType" use="required" />
  </xs:complexType>

  <xs:complexType name="relationType">
    <xs:all>
      <xs:element name="virtualEndPoint" type="m:virtualEndPointType" />
      <xs:element name="endPoint" type="m:endPointType" />
    </xs:all>
    <xs:attribute name="id" type="t:requiredStringType" use="required" />
  </xs:complexType>

  <xs:complexType name="virtualEndPointType">
    <xs:complexContent>
      <xs:extension base="m:endPointBaseType">
        <xs:sequence>
          <xs:element name="property">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="collectionType" type="t:dotNetType" minOccurs="0" />
              </xs:sequence>
              <xs:attribute name="name" type="t:requiredStringType" use="required" /> 	  	              
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="cardinality" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="one" />
              <xs:enumeration value="many" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="endPointType">
    <xs:complexContent>
      <xs:extension base="m:endPointBaseType">
        <xs:sequence>
          <xs:element name="property">
            <xs:complexType>
              <xs:attribute name="name" type="t:requiredStringType" use="required" /> 	  	
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="endPointBaseType">
    <xs:sequence>
      <xs:element name="class">
      	<xs:complexType>
      		<xs:attribute name="id" type="t:requiredStringType" use="required" />
      	</xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="isMandatory" type="xs:boolean" use="required" />
  </xs:complexType>

  <xs:simpleType name="positiveIntType">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="simpleTypeOrDotNetType">
    <xs:union memberTypes="m:simpleType t:dotNetType" />
  </xs:simpleType>

  <xs:simpleType name="simpleType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="boolean" />
      <xs:enumeration value="byte" />
      <xs:enumeration value="date" />
      <xs:enumeration value="dateTime" />
      <xs:enumeration value="decimal" />
      <xs:enumeration value="double" />
      <xs:enumeration value="guid" />
      <xs:enumeration value="int16" />
      <xs:enumeration value="int32" />
      <xs:enumeration value="int64" />
      <xs:enumeration value="single" />
      <xs:enumeration value="string" />
      <xs:enumeration value="char" />
      <xs:enumeration value="objectID" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== re-motion/Framework-Archive/Data/DomainObjects.UnitTests/mappingWithColumnAndCardinalityMany.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="UnitTests" 
    xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\mapping.xsd">
	<classes>
		<class id="Order">
			<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Order, Rubicon.Data.DomainObjects.UnitTests</type>
			<entity name="Order" />
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="OrderNumber">
					<type>int32</type>
					<column>OrderNo</column>
				</property>
				<property name="DeliveryDate">
					<type>dateTime</type>
					<column>DeliveryDate</column>
				</property>
				<relationProperty name="OrderTicket" relationID="OrderToOrderTicket" cardinality="one" isMandatory="true" />
			</properties>
		</class>
		<class id="OrderTicket">
			<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.OrderTicket, Rubicon.Data.DomainObjects.UnitTests</type>
			<entity name="OrderTicket" />
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="FileName">
					<type>string</type>
					<column>FileName</column>
					<maxLength>255</maxLength>
				</property>
				<relationProperty name="Order" relationID="OrderToOrderTicket" cardinality="many" isMandatory="true">
					<column>OrderID</column>
				</relationProperty>
			</properties>
		</class>
	</classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.UnitTests/mappingWithDerivationAndDuplicateColumnName.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="UnitTests" 
    xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\DomainObjects\mapping.xsd">
  <classes>
		<class id="Customer">
			<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Customer, Rubicon.Data.DomainObjects.UnitTests</type>
			<entity name="Company" />
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="CustomerSince">
					<type>dateTime</type>
					<column>CustomerSince</column>
					<nullable>true</nullable>					
				</property>
				<property name="CustomerType">
					<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Customer+CustomerType, Rubicon.Data.DomainObjects.UnitTests</type>
					<column>CustomerType</column>
				</property>
				<relationProperty name="Orders" relationID="CustomerToOrder" cardinality="many" isMandatory="false" />
				<relationProperty name="SpecialOrders" relationID="CustomerToSpecialOrder" cardinality="many" isMandatory="false" />
			</properties>
		</class>
		<class id="Order">
			<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Order, Rubicon.Data.DomainObjects.UnitTests</type>
			<entity name="Order" />
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="OrderNumber">
					<type>int32</type>
					<column>OrderNo</column>
				</property>
				<property name="DeliveryDate">
					<type>dateTime</type>
					<column>DeliveryDate</column>
				</property>
				<relationProperty name="Customer" relationID="CustomerToOrder" cardinality="one" isMandatory="true">
					<column>CustomerID</column>
				</relationProperty>
			</properties>
		</class>
		<class id="SpecialOrder" baseClass="Order">
		  <!-- Use an arbitrary class name to avoid other exception while loading mapping file. -->
			<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.OrderTicket, Rubicon.Data.DomainObjects.UnitTests</type>
			<entity name="Order" />
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<relationProperty name="SpecialCustomer" relationID="CustomerToSpecialOrder" cardinality="one" isMandatory="true">
				  <!-- Mapping error: Inherited property 'Customer' already defines column 'CustomerID'. -->
					<column>CustomerID</column>
				</relationProperty>
			</properties>		
		</class>
  </classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.UnitTests/TableInheritance/TableInheritanceMapping.xml
<?xml version="1.0" encoding="UTF-8"?>

<mapping application="UnitTests" xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\..\DomainObjects\mapping.xsd">
	<classes>
    
		<class id="DomainBase">
			<type>Rubicon.Data.DomainObjects.UnitTests.TableInheritance.TestDomain.DomainBase, Rubicon.Data.DomainObjects.UnitTests</type>
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="CreatedBy">
					<type>string</type>
					<column>CreatedBy</column>
					<maxLength>100</maxLength>
				</property>
        <property name="CreatedAt">
          <type>dateTime</type>
          <column>CreatedAt</column>
        </property>
      </properties>
		</class>

    <class id="Person" baseClass="DomainBase">
      <type>Rubicon.Data.DomainObjects.UnitTests.TableInheritance.TestDomain.Person, Rubicon.Data.DomainObjects.UnitTests</type>
      <entity name="Person" />
      <storageProviderID>TestDomain</storageProviderID>
      <properties>
        <property name="FirstName">
          <type>string</type>
          <column>FirstName</column>
          <maxLength>100</maxLength>
        </property>
        <property name="LastName">
          <type>string</type>
          <column>LastName</column>
          <maxLength>100</maxLength>
        </property>
        <property name="DateOfBirth">
          <type>dateTime</type>
          <column>DateOfBirth</column>
        </property>
      </properties>
    </class>

    <class id="Organization" baseClass="DomainBase">
      <type>Rubicon.Data.DomainObjects.UnitTests.TableInheritance.TestDomain.Organization, Rubicon.Data.DomainObjects.UnitTests</type>
      <entity name="Organization" />
      <storageProviderID>TestDomain</storageProviderID>
      <properties>
        <property name="Name">
          <type>string</type>
          <column>Name</column>
          <maxLength>100</maxLength>
        </property>
        <property name="NumberOfEmployees">
          <type>int32</type>
          <column>NumberOfEmployees</column>
        </property>
      </properties>
    </class>

  </classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.PerformanceTests/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping application="PerformanceTests" xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\mapping.xsd">
	<classes>
		<class id="Client">
			<type>Rubicon.Data.DomainObjects.PerformanceTests.TestDomain.Client, Rubicon.Data.DomainObjects.PerformanceTests</type>
			<entity name="Client"></entity>
			<storageProviderID>PerformanceTestDomain</storageProviderID>
			<properties>
			  <property name="Name">
					<type>string</type>
					<column>Name</column>
					<maxLength>100</maxLength>
			  </property>
			  <relationProperty name="Files" relationID="ClientToFile" cardinality="many" isMandatory="false "/>
			</properties>
		</class>

		<class id="File">
			<type>Rubicon.Data.DomainObjects.PerformanceTests.TestDomain.File, Rubicon.Data.DomainObjects.PerformanceTests</type>
			<entity name="File"></entity>
			<storageProviderID>PerformanceTestDomain</storageProviderID>
			<properties>
			  <property name="Number">
					<type>string</type>
					<column>Number</column>
					<maxLength>100</maxLength>
			  </property>
			  <relationProperty name="Client" relationID="ClientToFile" cardinality="one" isMandatory="true">
			    <column>File</column>
			  </relationProperty>
			</properties>
		</class>
	</classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.UnitTests/Configuration/Mapping/TestMappings/MappingWithoutColumnElement.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="UnitTests" 
    xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\..\..\..\DomainObjects\Schemas\Mapping.xsd">
  <classes>
    <class id="Customer">
      <properties>
        <!-- Note: CustomerSince has no sub element column. -->
        <property name="CustomerSince">
          <type>dateTime</type>
          <nullable>true</nullable>
        </property>
        <property name="Type">
          <type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Customer+CustomerType, Rubicon.Data.DomainObjects.UnitTests</type>
          <column>CustomerType</column>
        </property>
      </properties>
      <storageProviderID>TestDomain</storageProviderID>
      <entity name="Company"/>
      <type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Customer, Rubicon.Data.DomainObjects.UnitTests</type>
    </class>
  </classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.UnitTests/Configuration/Mapping/TestMappings/mappingWithOppositeClassReferringToItself.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="UnitTests" 
    xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\..\..\..\DomainObjects\Schemas\Mapping.xsd">
  <classes>
		<class id="Customer">
			<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Customer, Rubicon.Data.DomainObjects.UnitTests</type>
			<entity name="Company" />
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
			  <relationProperty name="Orders" relationID="CustomerToOrder" isMandatory="false" cardinality="many">
			  	  <column>InvalidColumn</column>	
			    <oppositeClass>Order</oppositeClass>
			  </relationProperty>			  
			</properties>
		</class>
  </classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.UnitTests/mappingWithPropertyDefinedInBaseOfBaseClassAndDerivedClass.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="UnitTests" 
    xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping ..\mapping.xsd">
	<classes>
		<class id="Company">
			<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Company, Rubicon.Data.DomainObjects.UnitTests</type>
			<entity>Company</entity>
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="Name">
					<type>string</type>
					<column>Name</column>
					<maxLength>100</maxLength>
				</property>
				<property name="IndustrialSector">
				  <type>objectID</type>
				  <column>IndustrialSectorID</column>
				</property>
			</properties>
		</class>
		<class id="Partner" baseClass="Company">
			<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Partner, Rubicon.Data.DomainObjects.UnitTests</type>
			<entity>Company</entity>
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="ContactPerson">
					<type>objectID</type>
					<column>ContactPersonID</column>
				</property>
			</properties>
		</class>
		<class id="Supplier" baseClass="Partner">
			<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Supplier, Rubicon.Data.DomainObjects.UnitTests</type>
			<entity>Company</entity>
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="Name">
					<type>string</type>
					<column>Name</column>
					<maxLength>100</maxLength>
				</property>
				<property name="SupplierQuality">
					<type>int32</type>
					<column>SupplierQuality</column>
				</property>
			</properties>
		</class>
	</classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.UnitTests/Configuration/Mapping/TestMappings/mappingWithDuplicateColumnName.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="UnitTests" 
    xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\..\..\..\DomainObjects\mapping.xsd">
  <classes>
		<class id="Customer">
			<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Customer, Rubicon.Data.DomainObjects.UnitTests</type>
			<entity name="Company" />
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="CustomerSince">
					<type>dateTime</type>
					<column>CustomerSince</column>
					<nullable>true</nullable>					
				</property>
				<property name="Type">
					<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Customer+CustomerType, Rubicon.Data.DomainObjects.UnitTests</type>
					<!-- The column does not comply with mapping, because property 'CustomerSince' already refers to it. -->
					<column>CustomerSince</column>
				</property>
			</properties>
		</class>
  </classes>
</mapping>
