=== re-motion/Framework-Archive/Data/DomainObjects.Web.Test/bin/mapping.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:m="http://www.rubicon-it.com/Data/DomainObjects/Mapping" xmlns:t="http://www.rubicon-it.com/Data/DomainObjects/Types" elementFormDefault="qualified" attributeFormDefault="unqualified" targetNamespace="http://www.rubicon-it.com/Data/DomainObjects/Mapping" xml:lang="en">

  <xs:import namespace="http://www.rubicon-it.com/Data/DomainObjects/Types" schemaLocation="types.xsd" />

  <xs:element name="mapping">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="classes" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="class" type="m:classType" maxOccurs="unbounded">

                <xs:key name="propertyKey">
                  <xs:selector xpath="m:properties/m:property" />
                  <xs:field xpath="@name" />
                </xs:key>

              </xs:element>
            </xs:sequence>
          </xs:complexType>

        </xs:element>
        <xs:element name="relations" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="relation" type="m:relationType" maxOccurs="unbounded" />
            </xs:sequence>
          </xs:complexType>

          <xs:key name="relationKey">
            <xs:selector xpath="m:relation" />
            <xs:field xpath="@id" />
          </xs:key>

          <xs:key name="relationClassPropertyKey">
            <xs:selector xpath="m:relation/m:*" />
            <xs:field xpath="m:class/@id" />
            <xs:field xpath="m:property/@name" />
          </xs:key>

        </xs:element>
      </xs:sequence>
      <xs:attribute name="application" type="t:requiredStringType" use="required" />
    </xs:complexType>

    <xs:key name="classKey">
      <xs:selector xpath="m:classes/m:class" />
      <xs:field xpath="@id" />
    </xs:key>

    <xs:keyref name="endPointToClass" refer="m:classKey">
      <xs:selector xpath="m:relations/m:relation/m:*" />
      <xs:field xpath="m:class/@id" />
    </xs:keyref>

  </xs:element>

  <xs:complexType name="classType">
    <xs:sequence>
      <xs:element name="type" type="t:dotNetType" />
      <xs:element name="entity" type="t:requiredStringType" />
      <xs:element name="storageProviderID" type="t:requiredStringType" />
      <xs:element name="properties">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="property" type="m:propertyType" minOccurs="0" maxOccurs="unbounded" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="t:requiredStringType" use="required" />
    <xs:attribute name="baseClass" type="t:requiredStringType" use="optional" />
  </xs:complexType>

  <xs:complexType name="propertyType">
    <xs:sequence>
      <xs:element name="type" type="m:simpleTypeOrDotNetType" />
      <xs:element name="column" type="t:requiredStringType" />
      <xs:element name="nullable" type="xs:boolean" minOccurs="0" />
      <xs:element name="maxLength" type="m:positiveIntType" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="name" type="t:requiredStringType" use="required" />
  </xs:complexType>

  <xs:complexType name="relationType">
    <xs:all>
      <xs:element name="virtualEndPoint" type="m:virtualEndPointType" />
      <xs:element name="endPoint" type="m:endPointType" />
    </xs:all>
    <xs:attribute name="id" type="t:requiredStringType" use="required" />
  </xs:complexType>

  <xs:complexType name="virtualEndPointType">
    <xs:complexContent>
      <xs:extension base="m:endPointBaseType">
        <xs:sequence>
          <xs:element name="property">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="collectionType" type="t:dotNetType" minOccurs="0" />
              </xs:sequence>
              <xs:attribute name="name" type="t:requiredStringType" use="required" /> 	  	              
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="cardinality" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="one" />
              <xs:enumeration value="many" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="endPointType">
    <xs:complexContent>
      <xs:extension base="m:endPointBaseType">
        <xs:sequence>
          <xs:element name="property">
            <xs:complexType>
              <xs:attribute name="name" type="t:requiredStringType" use="required" /> 	  	
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="endPointBaseType">
    <xs:sequence>
      <xs:element name="class">
      	<xs:complexType>
      		<xs:attribute name="id" type="t:requiredStringType" use="required" />
      	</xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="isMandatory" type="xs:boolean" use="required" />
  </xs:complexType>

  <xs:simpleType name="positiveIntType">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="simpleTypeOrDotNetType">
    <xs:union memberTypes="m:simpleType t:dotNetType" />
  </xs:simpleType>

  <xs:simpleType name="simpleType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="boolean" />
      <xs:enumeration value="byte" />
      <xs:enumeration value="date" />
      <xs:enumeration value="dateTime" />
      <xs:enumeration value="decimal" />
      <xs:enumeration value="double" />
      <xs:enumeration value="guid" />
      <xs:enumeration value="int16" />
      <xs:enumeration value="int32" />
      <xs:enumeration value="int64" />
      <xs:enumeration value="single" />
      <xs:enumeration value="string" />
      <xs:enumeration value="char" />
      <xs:enumeration value="objectID" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== re-motion/Framework-Archive/Data/DomainObjects.ObjectBinding.UnitTests/mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping application="UnitTests" xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\DomainObjects\mapping.xsd">
	<classes>
		<class id="Order">
			<type>Rubicon.Data.DomainObjects.ObjectBinding.UnitTests.TestDomain.Order, Rubicon.Data.DomainObjects.ObjectBinding.UnitTests</type>
			<entity name="Order"/>
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="OrderNumber">
					<type>int32</type>
					<column>OrderNo</column>
				</property>
				<property name="DeliveryDate">
					<type>dateTime</type>
					<column>DeliveryDate</column>
				</property>
				<relationProperty name="OrderTicket" relationID="OrderToOrderTicket" cardinality="one" isMandatory="true"/>
				<relationProperty name="OrderItems" relationID="OrderToOrderItem" cardinality="many" isMandatory="true"/>
			</properties>
		</class>
		<class id="OrderItem">
			<type>Rubicon.Data.DomainObjects.ObjectBinding.UnitTests.TestDomain.OrderItem, Rubicon.Data.DomainObjects.ObjectBinding.UnitTests</type>
			<entity name="OrderItem"/>
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="Position">
					<type>int32</type>
					<column>Position</column>
				</property>
				<property name="Product">
					<type>string</type>
					<column>Product</column>
					<maxLength>100</maxLength>
				</property>
				<relationProperty name="Order" relationID="OrderToOrderItem" cardinality="one" isMandatory="true">
					<column>OrderID</column>
				</relationProperty>
			</properties>
		</class>
		<class id="OrderTicket">
			<type>Rubicon.Data.DomainObjects.ObjectBinding.UnitTests.TestDomain.OrderTicket, Rubicon.Data.DomainObjects.ObjectBinding.UnitTests</type>
			<entity name="OrderTicket"/>
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="FileName">
					<type>string</type>
					<column>FileName</column>
					<maxLength>255</maxLength>
				</property>
				<relationProperty name="Order" relationID="OrderToOrderTicket" cardinality="one" isMandatory="true">
					<column>OrderID</column>
				</relationProperty>
			</properties>
		</class>
	</classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.Legacy.UnitTests/Configuration/Mapping/TestMappings/DataDomainObjectsLegacy_MappingWithInvalidDerivationAcrossStorageProviders.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="UnitTests" 
    xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\..\..\..\DomainObjects\Schemas\Mapping.xsd">
    
  <classes>
		<class id="Company">
			<type>Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.Company, Remotion.Data.DomainObjects.Legacy.UnitTests</type>
			<entity name="Company" />
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="Name">
					<type>string</type>
					<column>Name</column>
					<maxLength>100</maxLength>
				</property>
			</properties>
		</class>
		<class id="Customer" baseClass="Company">
			<type>Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.Customer, Remotion.Data.DomainObjects.Legacy.UnitTests</type>
			<entity name="Company" />
			<storageProviderID>OtherStorageProvider</storageProviderID>
			<properties>
				<property name="CustomerSince">
					<type>dateTime</type>
					<column>CustomerSince</column>
					<nullable>true</nullable>					
				</property>
				<property name="Type">
					<type>Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.Customer+CustomerType, Remotion.Data.DomainObjects.Legacy.UnitTests</type>
					<column>CustomerType</column>
				</property>
			</properties>
		</class>
  </classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.Legacy.UnitTests/Configuration/Mapping/TestMappings/DataDomainObjectsLegacy_MappingWithPropertyDefinedInTwoBaseClasses.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="UnitTests" 
    xmlns="http://www.re-motion.org/Data/DomainObjects/Mapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.re-motion.org/Data/DomainObjects/Mapping/1.0 ..\..\..\..\DomainObjects\Schemas\Mapping.xsd">
	<classes>

    <!-- Note: Supplier must be defined before Partner is defined! -->
    <class id="Supplier" baseClass="Partner">
      <type>Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.Supplier, Remotion.Data.DomainObjects.Legacy.UnitTests</type>
      <entity name="Company" />
      <storageProviderID>TestDomain</storageProviderID>
      <properties>
      </properties>
    </class>

    <!-- Note: Partner must be defined after Supplier is defined! -->
    <class id="Partner" baseClass="Company">
      <type>Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.Partner, Remotion.Data.DomainObjects.Legacy.UnitTests</type>
      <entity name="Company" />
      <storageProviderID>TestDomain</storageProviderID>
      <properties>
        <!-- Note: Base class Company defines the same property. -->
        <property name="Name">
          <type>string</type>
          <column>PartnerName</column>
          <maxLength>100</maxLength>
        </property>
      </properties>
    </class>

    <class id="Company">
      <type>Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.Company, Remotion.Data.DomainObjects.Legacy.UnitTests</type>
      <entity name="Company" />
      <storageProviderID>TestDomain</storageProviderID>
      <properties>
        <property name="Name">
          <type>string</type>
          <column>CompanyName</column>
          <maxLength>100</maxLength>
        </property>
      </properties>
    </class>
  </classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.UnitTests/mappingWithPropertyDefinedInBaseAndDerivedClass.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="UnitTests" 
    xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\mapping.xsd">
  <classes>
		<class id="Company">
			<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Company, Rubicon.Data.DomainObjects.UnitTests</type>
			<entity name="Company" />
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="Name">
					<type>string</type>
					<column>Name</column>
					<maxLength>100</maxLength>
				</property>
			</properties>
		</class>
		<class id="Customer" baseClass="Company">
			<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Customer, Rubicon.Data.DomainObjects.UnitTests</type>
			<entity name="Company" />
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="Name">
					<type>string</type>
					<column>Name</column>
					<maxLength>100</maxLength>
				</property>
				<property name="CustomerSince">
					<type>dateTime</type>
					<column>CustomerSince</column>
					<nullable>true</nullable>					
				</property>
				<property name="CustomerType">
					<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Customer+CustomerType, Rubicon.Data.DomainObjects.UnitTests</type>
					<column>CustomerType</column>
				</property>
			</properties>
		</class>
  </classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.UnitTests/mappingWithUnresolvedTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping application="UnitTests" xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\DomainObjects\mapping.xsd">
	<classes>
		<class id="ClassWithUnresolvedTypes">
			<type>UnknownClassType, Rubicon.Data.DomainObjects.UnitTests</type>
			<entity name="TableWithUnresolvedTypes"/>
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="Int32Property">
					<type>int32</type>
					<column>Int32Column</column>
				</property>
				<property name="EnumProperty">
					<type>UnknownClassType+EnumType, Rubicon.Data.DomainObjects.UnitTests</type>
					<column>EnumColumn</column>
				</property>
			</properties>
		</class>
	</classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.UnitTests/mappingWithCollectionTypeAndOneToOneRelation.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="UnitTests" 
    xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\mapping.xsd">
	<classes>
		<class id="Order">
			<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Order, Rubicon.Data.DomainObjects.UnitTests</type>
			<entity>Order</entity>
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="OrderNumber">
					<type>int32</type>
					<column>OrderNo</column>
				</property>
				<property name="DeliveryDate">
					<type>dateTime</type>
					<column>DeliveryDate</column>
				</property>
				<property name="Customer">
					<type>objectID</type>
					<column>CustomerID</column>
				</property>
				<property name="Official">
					<type>objectID</type>
					<column>OfficialID</column>
				</property>				
			</properties>
		</class>
		<class id="OrderTicket">
			<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.OrderTicket, Rubicon.Data.DomainObjects.UnitTests</type>
			<entity>OrderTicket</entity>
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="FileName">
					<type>string</type>
					<column>FileName</column>
					<maxLength>255</maxLength>
				</property>
				<property name="Order">
					<type>objectID</type>
					<column>OrderID</column>
				</property>
			</properties>
		</class>
	</classes>

	
	<relations>
		<relation id="OrderToOrderTicket">
			<virtualEndPoint cardinality="one" isMandatory="true">
				<class id="Order" />
				<property name="OrderTicket">
					<!-- Line below is invalid for virtualEndPoint with cardinality="one" -->
					<collectionType>Rubicon.Data.DomainObjects.DomainObjectCollection, Rubicon.Data.DomainObjects</collectionType>
				</property>	
			</virtualEndPoint>
			<endPoint isMandatory="true">
				<class id="OrderTicket" />
				<property name="Order" />
			</endPoint>
		</relation>
	</relations>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.Legacy.UnitTests/Configuration/Mapping/TestMappings/DataDomainObjectsLegacy_MappingWithResolvedTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping application="UnitTests" xmlns="http://www.re-motion.org/Data/DomainObjects/Mapping/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.re-motion.org/Data/DomainObjects/Mapping/1.0 ..\..\..\..\DomainObjects\Schemas\Mapping.xsd">
	<classes>
		<class id="Customer">
		  <!-- Note: Type contains leading and trailing whitespace -->
			<type>
			  Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.Customer, Remotion.Data.DomainObjects.Legacy.UnitTests
			</type>
			<entity name="Company"/>
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="CustomerSince">
					<type>dateTime</type>
					<column>CustomerSince</column>
					<nullable>true</nullable>
				</property>
				<property name="Type">
				  <!-- Note: Type contains leading and trailing whitespace -->
					<type>
					  Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.Customer+CustomerType, Remotion.Data.DomainObjects.Legacy.UnitTests
					</type>
					<column>CustomerType</column>
				</property>
				<relationProperty name="Orders" relationID="CustomerToOrder" cardinality="many" isMandatory="false">
				  <!-- Note: Type contains leading and trailing whitespace -->
					<collectionType>
						Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.OrderCollection, Remotion.Data.DomainObjects.Legacy.UnitTests
					</collectionType>
					<sortExpression>OrderNo asc</sortExpression>
				</relationProperty>
			</properties>
		</class>
		<class id="Order">
			<type>Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.Order, Remotion.Data.DomainObjects.Legacy.UnitTests</type>
			<entity name="Order"/>
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="OrderNumber">
					<type>int32</type>
					<column>OrderNo</column>
				</property>
				<property name="DeliveryDate">
					<type>dateTime</type>
					<column>DeliveryDate</column>
				</property>
				<relationProperty name="Customer" relationID="CustomerToOrder" cardinality="one" isMandatory="true">
					<column>CustomerID</column>
				</relationProperty>				
				<relationProperty name="OrderTicket" relationID="OrderToOrderTicket" cardinality="one" isMandatory="true"/>
				<relationProperty name="OrderItems" relationID="OrderToOrderItem" cardinality="many" isMandatory="true"/>
			</properties>
		</class>
		<class id="OrderItem">
			<type>Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.OrderItem, Remotion.Data.DomainObjects.Legacy.UnitTests</type>
			<entity name="OrderItem"/>
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="Position">
					<type>int32</type>
					<column>Position</column>
				</property>
				<property name="Product">
					<type>string</type>
					<column>Product</column>
					<maxLength>100</maxLength>
				</property>
				<relationProperty name="Order" relationID="OrderToOrderItem" cardinality="one" isMandatory="true">
					<column>OrderID</column>
				</relationProperty>
			</properties>
		</class>
		<class id="OrderTicket">
			<type>Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.OrderTicket, Remotion.Data.DomainObjects.Legacy.UnitTests</type>
			<entity name="OrderTicket"/>
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="FileName">
					<type>string</type>
					<column>FileName</column>
					<maxLength>255</maxLength>
				</property>
				<relationProperty name="Order" relationID="OrderToOrderTicket" cardinality="one" isMandatory="true">
					<column>OrderID</column>
				</relationProperty>
			</properties>
		</class>
	</classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.Legacy.UnitTests/Configuration/Mapping/TestMappings/DataDomainObjectsLegacy_MappingWithUnorderedElements.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="UnitTests" 
    xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\..\..\..\DomainObjects\Schemas\Mapping.xsd">
  <classes>
    <!-- Note: The subelements of class are unordered. -->
    <class id="Customer">
      <properties>
        <!-- Note: The subelements of property are unordered. -->
        <property name="CustomerSince">
          <type>dateTime</type>
          <column>CustomerSince</column>
          <nullable>true</nullable>
        </property>
        <property name="Type">
          <type>Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.Customer+CustomerType, Remotion.Data.DomainObjects.Legacy.UnitTests</type>
          <column>CustomerType</column>
        </property>
        <relationProperty name="Orders" relationID="CustomerToOrder" cardinality="many" isMandatory="false">
          <collectionType>Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.OrderCollection, Remotion.Data.DomainObjects.Legacy.UnitTests</collectionType>
          <sortExpression>OrderNo asc</sortExpression>
        </relationProperty>
      </properties>
      <storageProviderID>TestDomain</storageProviderID>
      <entity name="Company"/>
      <type>Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.Customer, Remotion.Data.DomainObjects.Legacy.UnitTests</type>
    </class>
    <class id="Order">
      <type>Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.Order, Remotion.Data.DomainObjects.Legacy.UnitTests</type>
      <entity name="Order"/>
      <storageProviderID>TestDomain</storageProviderID>
      <properties>
        <property name="OrderNumber">
          <type>int32</type>
          <column>OrderNo</column>
        </property>
        <property name="DeliveryDate">
          <type>dateTime</type>
          <column>DeliveryDate</column>
        </property>
        <relationProperty name="Customer" relationID="CustomerToOrder" cardinality="one" isMandatory="true">
          <column>CustomerID</column>
        </relationProperty>
        <relationProperty name="OrderTicket" relationID="OrderToOrderTicket" cardinality="one" isMandatory="true"/>
        <relationProperty name="OrderItems" relationID="OrderToOrderItem" cardinality="many" isMandatory="true"/>
        <relationProperty name="Official" relationID="OfficialToOrder" cardinality="one" isMandatory="true">
          <column>OfficialID</column>
          <oppositeClass>Official</oppositeClass>
        </relationProperty>
      </properties>
    </class>
    <class id="Official">
      <type>Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.Official, Remotion.Data.DomainObjects.Legacy.UnitTests</type>
      <entity name="Official"/>
      <storageProviderID>UnitTestStorageProviderStub</storageProviderID>
      <properties>
        <property name="Name">
          <type>string</type>
          <column>Name</column>
          <maxLength>100</maxLength>
        </property>
      </properties>
    </class>
  </classes>
</mapping>
