=== re-motion/Framework-Archive/Data/DomainObjects.Web.Test/bin/mapping.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:m="http://www.rubicon-it.com/Data/DomainObjects/Mapping" xmlns:t="http://www.rubicon-it.com/Data/DomainObjects/Types" elementFormDefault="qualified" attributeFormDefault="unqualified" targetNamespace="http://www.rubicon-it.com/Data/DomainObjects/Mapping" xml:lang="en">

  <xs:import namespace="http://www.rubicon-it.com/Data/DomainObjects/Types" schemaLocation="types.xsd" />

  <xs:element name="mapping">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="classes" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="class" type="m:classType" maxOccurs="unbounded">

                <xs:key name="propertyKey">
                  <xs:selector xpath="m:properties/m:property" />
                  <xs:field xpath="@name" />
                </xs:key>

              </xs:element>
            </xs:sequence>
          </xs:complexType>

        </xs:element>
        <xs:element name="relations" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="relation" type="m:relationType" maxOccurs="unbounded" />
            </xs:sequence>
          </xs:complexType>

          <xs:key name="relationKey">
            <xs:selector xpath="m:relation" />
            <xs:field xpath="@id" />
          </xs:key>

          <xs:key name="relationClassPropertyKey">
            <xs:selector xpath="m:relation/m:*" />
            <xs:field xpath="m:class/@id" />
            <xs:field xpath="m:property/@name" />
          </xs:key>

        </xs:element>
      </xs:sequence>
      <xs:attribute name="application" type="t:requiredStringType" use="required" />
    </xs:complexType>

    <xs:key name="classKey">
      <xs:selector xpath="m:classes/m:class" />
      <xs:field xpath="@id" />
    </xs:key>

    <xs:keyref name="endPointToClass" refer="m:classKey">
      <xs:selector xpath="m:relations/m:relation/m:*" />
      <xs:field xpath="m:class/@id" />
    </xs:keyref>

  </xs:element>

  <xs:complexType name="classType">
    <xs:sequence>
      <xs:element name="type" type="t:dotNetType" />
      <xs:element name="entity" type="t:requiredStringType" />
      <xs:element name="storageProviderID" type="t:requiredStringType" />
      <xs:element name="properties">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="property" type="m:propertyType" minOccurs="0" maxOccurs="unbounded" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="t:requiredStringType" use="required" />
    <xs:attribute name="baseClass" type="t:requiredStringType" use="optional" />
  </xs:complexType>

  <xs:complexType name="propertyType">
    <xs:sequence>
      <xs:element name="type" type="m:simpleTypeOrDotNetType" />
      <xs:element name="column" type="t:requiredStringType" />
      <xs:element name="nullable" type="xs:boolean" minOccurs="0" />
      <xs:element name="maxLength" type="m:positiveIntType" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="name" type="t:requiredStringType" use="required" />
  </xs:complexType>

  <xs:complexType name="relationType">
    <xs:all>
      <xs:element name="virtualEndPoint" type="m:virtualEndPointType" />
      <xs:element name="endPoint" type="m:endPointType" />
    </xs:all>
    <xs:attribute name="id" type="t:requiredStringType" use="required" />
  </xs:complexType>

  <xs:complexType name="virtualEndPointType">
    <xs:complexContent>
      <xs:extension base="m:endPointBaseType">
        <xs:sequence>
          <xs:element name="property">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="collectionType" type="t:dotNetType" minOccurs="0" />
              </xs:sequence>
              <xs:attribute name="name" type="t:requiredStringType" use="required" /> 	  	              
            </xs:complexType>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="cardinality" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="one" />
              <xs:enumeration value="many" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="endPointType">
    <xs:complexContent>
      <xs:extension base="m:endPointBaseType">
        <xs:sequence>
          <xs:element name="property">
            <xs:complexType>
              <xs:attribute name="name" type="t:requiredStringType" use="required" /> 	  	
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="endPointBaseType">
    <xs:sequence>
      <xs:element name="class">
      	<xs:complexType>
      		<xs:attribute name="id" type="t:requiredStringType" use="required" />
      	</xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="isMandatory" type="xs:boolean" use="required" />
  </xs:complexType>

  <xs:simpleType name="positiveIntType">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="simpleTypeOrDotNetType">
    <xs:union memberTypes="m:simpleType t:dotNetType" />
  </xs:simpleType>

  <xs:simpleType name="simpleType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="boolean" />
      <xs:enumeration value="byte" />
      <xs:enumeration value="date" />
      <xs:enumeration value="dateTime" />
      <xs:enumeration value="decimal" />
      <xs:enumeration value="double" />
      <xs:enumeration value="guid" />
      <xs:enumeration value="int16" />
      <xs:enumeration value="int32" />
      <xs:enumeration value="int64" />
      <xs:enumeration value="single" />
      <xs:enumeration value="string" />
      <xs:enumeration value="char" />
      <xs:enumeration value="objectID" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== re-motion/Framework-Archive/Data/DomainObjects.Web.Test/Mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="RplObjectBindingTest" 
    xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\DomainObjects\Schemas\Mapping.xsd">
	<classes>
		<class id="ClassWithAllDataTypes">
			<type>Rubicon.Data.DomainObjects.Web.Test.Domain.ClassWithAllDataTypes, Rubicon.Data.DomainObjects.Web.Test</type>
			<entity name="TableWithAllDataTypes" />
			<storageProviderID>RpaTest</storageProviderID>
			<properties>
				<property name="BooleanProperty">
					<type>boolean</type>
					<column>Boolean</column>
				</property>
				<property name="ByteProperty">
					<type>byte</type>
					<column>Byte</column>
				</property>
				<property name="DateProperty">
					<type>date</type>
					<column>Date</column>
				</property>
				<property name="DateTimeProperty">
					<type>dateTime</type>
					<column>DateTime</column>
				</property>
				<property name="DecimalProperty">
					<type>decimal</type>
					<column>Decimal</column>
				</property>
				<property name="DoubleProperty">
					<type>double</type>
					<column>Double</column>
				</property>
				<property name="EnumProperty">
					<type>Rubicon.Data.DomainObjects.Web.Test.Domain.ClassWithAllDataTypes+EnumType, Rubicon.Data.DomainObjects.Web.Test</type>
					<column>Enum</column>
				</property>
				<property name="GuidProperty">
					<type>guid</type>
					<column>Guid</column>
				</property>
				<property name="Int16Property">
					<type>int16</type>
					<column>Int16</column>
				</property>
				<property name="Int32Property">
					<type>int32</type>
					<column>Int32</column>
				</property>
				<property name="Int64Property">
					<type>int64</type>
					<column>Int64</column>
				</property>
				<property name="SingleProperty">
					<type>single</type>
					<column>Single</column>
				</property>
				<property name="StringProperty">
					<type>string</type>
					<column>String</column>
					<maxLength>100</maxLength>
				</property>
				<property name="DelimitedStringArrayProperty">
					<type>string</type>
					<column>DelimitedStringArray</column>
					<maxLength>1000</maxLength>
				</property>
				<property name="BinaryProperty">
					<type>binary</type>
					<column>Binary</column>
				</property>
				<property name="NaBooleanProperty">
					<type>boolean</type>
					<column>NaBoolean</column>
					<nullable>true</nullable>
				</property>
        <property name="NaByteProperty">
          <type>byte</type>
          <column>NaByte</column>
          <nullable>true</nullable>
        </property>
				<property name="NaDateProperty">
					<type>date</type>
					<column>NaDate</column>
					<nullable>true</nullable>
				</property>
				<property name="NaDateTimeProperty">
					<type>dateTime</type>
					<column>NaDateTime</column>
					<nullable>true</nullable>
				</property>
        <property name="NaDecimalProperty">
          <type>decimal</type>
          <column>NaDecimal</column>
          <nullable>true</nullable>
        </property>
				<property name="NaDoubleProperty">
					<type>double</type>
					<column>NaDouble</column>
					<nullable>true</nullable>
				</property>
        <property name="NaGuidProperty">
          <type>guid</type>
          <column>NaGuid</column>
          <nullable>true</nullable>
        </property>
        <property name="NaInt16Property">
          <type>int16</type>
          <column>NaInt16</column>
          <nullable>true</nullable>
        </property>
				<property name="NaInt32Property">
					<type>int32</type>
					<column>NaInt32</column>
					<nullable>true</nullable>
				</property>
        <property name="NaInt64Property">
          <type>int64</type>
          <column>NaInt64</column>
          <nullable>true</nullable>
        </property>
        <property name="NaSingleProperty">
          <type>single</type>
          <column>NaSingle</column>
          <nullable>true</nullable>
        </property>
				<property name="StringWithNullValueProperty">
					<type>string</type>
					<column>StringWithNullValue</column>
					<nullable>true</nullable>
					<maxLength>100</maxLength>
				</property>
				<property name="DelimitedNullStringArrayProperty">
					<type>string</type>
					<column>DelimitedNullStringArray</column>
					<nullable>true</nullable>
					<maxLength>1000</maxLength>
				</property>
				<property name="NaBooleanWithNullValueProperty">
					<type>boolean</type>
					<column>NaBooleanWithNullValue</column>
					<nullable>true</nullable>
				</property>
        <property name="NaByteWithNullValueProperty">
          <type>byte</type>
          <column>NaByteWithNullValue</column>
          <nullable>true</nullable>
        </property>
				<property name="NaDateWithNullValueProperty">
					<type>date</type>
					<column>NaDateWithNullValue</column>
					<nullable>true</nullable>
				</property>
				<property name="NaDateTimeWithNullValueProperty">
					<type>dateTime</type>
					<column>NaDateTimeWithNullValue</column>
					<nullable>true</nullable>
				</property>
        <property name="NaDecimalWithNullValueProperty">
          <type>decimal</type>
          <column>NaDecimalWithNullValue</column>
          <nullable>true</nullable>
        </property>
				<property name="NaDoubleWithNullValueProperty">
					<type>double</type>
					<column>NaDoubleWithNullValue</column>
					<nullable>true</nullable>
				</property>
        <property name="NaGuidWithNullValueProperty">
          <type>guid</type>
          <column>NaGuidWithNullValue</column>
          <nullable>true</nullable>
        </property>
        <property name="NaInt16WithNullValueProperty">
          <type>int16</type>
          <column>NaInt16WithNullValue</column>
          <nullable>true</nullable>
        </property>
				<property name="NaInt32WithNullValueProperty">
					<type>int32</type>
					<column>NaInt32WithNullValue</column>
					<nullable>true</nullable>
				</property>
        <property name="NaInt64WithNullValueProperty">
          <type>int64</type>
          <column>NaInt64WithNullValue</column>
          <nullable>true</nullable>
        </property>
        <property name="NaSingleWithNullValueProperty">
          <type>single</type>
          <column>NaSingleWithNullValue</column>
          <nullable>true</nullable>
        </property>        
				<property name="NullableBinaryProperty">
					<type>binary</type>
					<column>NullableBinary</column>
					<nullable>true</nullable>
					<maxLength>1000000</maxLength>
				</property>
				<relationProperty name="ClassForRelationTestMandatory" relationID="ClassWithAllDataTypesToClassForRelationTestMandatory" cardinality="one" isMandatory="true">
					<column>TableForRelationTestMandatory</column>
				</relationProperty>
				<relationProperty name="ClassForRelationTestOptional" relationID="ClassWithAllDataTypesToClassForRelationTestOptional" cardinality="one" isMandatory="false">
					<column>TableForRelationTestOptional</column>
				</relationProperty>
				<relationProperty name="ClassesForRelationTestMandatoryNavigateOnly" relationID="ClassForRelationTestToClassWithAllDataTypesMandatory" cardinality="many" isMandatory="true" />
				<relationProperty name="ClassesForRelationTestOptionalNavigateOnly" relationID="ClassForRelationTestToClassWithAllDataTypesOptional" cardinality="many" isMandatory="false" />
			</properties>
		</class>
				
		<class id="ClassForRelationTest">
			<type>Rubicon.Data.DomainObjects.Web.Test.Domain.ClassForRelationTest, Rubicon.Data.DomainObjects.Web.Test</type>
			<entity name="TableForRelationTest" />
			<storageProviderID>RpaTest</storageProviderID>
			<properties>
				<property name="Name">
					<type>string</type>
					<column>Name</column>
					<maxLength>100</maxLength>
				</property>
				<relationProperty name="ClassWithAllDataTypesMandatoryNavigateOnly" relationID="ClassWithAllDataTypesToClassForRelationTestMandatory" cardinality="one" isMandatory="true" />
				<relationProperty name="ClassWithAllDataTypesOptionalNavigateOnly" relationID="ClassWithAllDataTypesToClassForRelationTestOptional" cardinality="one" isMandatory="false" />
				<relationProperty name="ClassWithAllDataTypesMandatory" relationID="ClassForRelationTestToClassWithAllDataTypesMandatory" cardinality="one" isMandatory="true">
					<column>TableWithAllDataTypesMandatory</column>
				</relationProperty>
				<relationProperty name="ClassWithAllDataTypesOptional" relationID="ClassForRelationTestToClassWithAllDataTypesOptional" cardinality="one" isMandatory="false">
					<column>TableWithAllDataTypesOptional</column>
				</relationProperty>			
			</properties>
		</class>

    <class id="ClassWithoutProperties">
      <type>Rubicon.Data.DomainObjects.Web.Test.Domain.ClassWithoutProperties, Rubicon.Data.DomainObjects.Web.Test</type>    
      <entity name="TableWithoutColumns"></entity>
      <storageProviderID>RpaTest</storageProviderID>
      <properties />
    </class>
    
    <class id="ClassWithUndefinedEnum">
      <type>Rubicon.Data.DomainObjects.Web.Test.Domain.ClassWithUndefinedEnum, Rubicon.Data.DomainObjects.Web.Test</type>    
      <entity name="TableWithUndefinedEnum"></entity>
      <storageProviderID>RpaTest</storageProviderID>
      <properties>
        <property name="UndefinedEnum">
          <type>Rubicon.Data.DomainObjects.Web.Test.Domain.UndefinedEnum, Rubicon.Data.DomainObjects.Web.Test</type>
          <column>UndefinedEnum</column>
        </property>
      </properties>
    </class>
 
 	</classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.UnitTests/Configuration/Mapping/TestMappings/-MappingWithPropertyDefinedInBaseOfBaseClassAndDerivedClass.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="UnitTests" 
    xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\..\..\..\DomainObjects\Schemas\Mapping.xsd">
	<classes>
    <class id="Company">
      <type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Company, Rubicon.Data.DomainObjects.UnitTests</type>
      <entity name="Company" />
      <storageProviderID>TestDomain</storageProviderID>
      <properties>
        <property name="Name">
          <type>string</type>
          <column>Name</column>
          <maxLength>100</maxLength>
        </property>
      </properties>
    </class>

    <!-- Note: Supplier must be defined before Partner is defined! -->
    <class id="Supplier" baseClass="Partner">
			<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Supplier, Rubicon.Data.DomainObjects.UnitTests</type>
			<entity name="Company" />
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
        <!-- Note: Name is alread defined in base class Company, which is invalid. -->
				<property name="Name">
					<type>string</type>
          <!-- Note: Name property has different column name than same property in base class. -->
          <column>SupplierName</column> 
					<maxLength>100</maxLength>
				</property>
				<property name="SupplierQuality">
					<type>int32</type>
					<column>SupplierQuality</column>
				</property>
			</properties>
		</class>

    <!-- Note: Partner must be defined after Supplier is defined! -->
    <class id="Partner" baseClass="Company">
      <type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Partner, Rubicon.Data.DomainObjects.UnitTests</type>
      <entity name="Company" />
      <storageProviderID>TestDomain</storageProviderID>
      <properties />
    </class>
  </classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.Legacy.UnitTests/Configuration/Mapping/TestMappings/DataDomainObjectsLegacy_MappingWithOppositeClassAndCardinalityMany.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="UnitTests" 
    xmlns="http://www.re-motion.org/Data/DomainObjects/Mapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.re-motion.org/Data/DomainObjects/Mapping/1.0 ..\..\..\..\DomainObjects\Schemas\Mapping.xsd">
  <classes>
		<class id="Customer">
			<type>Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.Customer, Remotion.Data.DomainObjects.Legacy.UnitTests</type>
			<entity name="Company" />
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
			  <relationProperty name="Orders" relationID="CustomerToOrder" isMandatory="false" cardinality="many">
			  	<column>InvalidColumn</column>	
			    <oppositeClass>Order</oppositeClass>
			  </relationProperty>			  
			</properties>
		</class>
		<class id="Order">
			<type>Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.Order, Remotion.Data.DomainObjects.Legacy.UnitTests</type>
			<entity name="Order"/>
			<storageProviderID>TestDomain</storageProviderID>
			<properties />
		</class>		
  </classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.Legacy.UnitTests/Configuration/Mapping/TestMappings/MappingWithDuplicateColumnName.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="UnitTests" 
    xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\..\..\..\DomainObjects\Schemas\Mapping.xsd">
  <classes>
		<class id="Customer">
			<type>Rubicon.Data.DomainObjects.Legacy.UnitTests.TestDomain.Customer, Rubicon.Data.DomainObjects.Legacy.UnitTests</type>
			<entity name="Company" />
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="CustomerSince">
					<type>dateTime</type>
					<column>CustomerSince</column>
					<nullable>true</nullable>					
				</property>
				<property name="Type">
					<type>Rubicon.Data.DomainObjects.Legacy.UnitTests.TestDomain.Customer+CustomerType, Rubicon.Data.DomainObjects.Legacy.UnitTests</type>
					<!-- The column does not comply with mapping, because property 'CustomerSince' already refers to it. -->
					<column>CustomerSince</column>
				</property>
			</properties>
		</class>
  </classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.Legacy.UnitTests/Configuration/Mapping/TestMappings/DataDomainObjectsLegacy_MappingWithColumnAndCardinalityMany.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="UnitTests" 
    xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\..\..\..\DomainObjects\Schemas\Mapping.xsd">
	<classes>
		<class id="Order">
			<type>Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.Order, Remotion.Data.DomainObjects.Legacy.UnitTests</type>
			<entity name="Order" />
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="OrderNumber">
					<type>int32</type>
					<column>OrderNo</column>
				</property>
				<property name="DeliveryDate">
					<type>dateTime</type>
					<column>DeliveryDate</column>
				</property>
				<relationProperty name="OrderTicket" relationID="OrderToOrderTicket" cardinality="one" isMandatory="true" />
			</properties>
		</class>
		<class id="OrderTicket">
			<type>Remotion.Data.DomainObjects.Legacy.UnitTests.TestDomain.OrderTicket, Remotion.Data.DomainObjects.Legacy.UnitTests</type>
			<entity name="OrderTicket" />
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="FileName">
					<type>string</type>
					<column>FileName</column>
					<maxLength>255</maxLength>
				</property>
				<relationProperty name="Order" relationID="OrderToOrderTicket" cardinality="many" isMandatory="true">
					<column>OrderID</column>
				</relationProperty>
			</properties>
		</class>
	</classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.UnitTests/mappingWithSchemaException.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="UnitTests" 
    xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping ..\mapping.xsd">
  <classes>
		<class id="Company">
			<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Company, Rubicon.Data.DomainObjects.UnitTests</type>
			<entity>Company</entity>
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<property name="Name">
					<!-- "unknownType" generates a MappingException when file is loaded. -->
					<type>unknownType</type>
					<column>Name</column>
				</property>
			</properties>
		</class>
  </classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects/UnitTests/mappingWithOnlyOneEndPoint.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="UnitTests" 
    xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\mapping.xsd">
  <classes>
		<class id="Order">
			<type>Rubicon.Data.DomainObjects.UnitTests.TestDomain.Order, Rubicon.Data.DomainObjects.UnitTests</type>
			<entity name="Order" />
			<storageProviderID>TestDomain</storageProviderID>
			<properties>
				<relationProperty name="Customer" relationID="CustomerToOrder" cardinality="one" isMandatory="true">
					<column>CustomerID</column>
				</relationProperty>
			</properties>
		</class>
  </classes>
</mapping>

=== re-motion/Framework-Archive/Data/DomainObjects.Legacy.UnitTests/Configuration/Mapping/TestMappings/DataDomainObjectsLegacy_MappingWithNonExistingBaseClass.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapping 
    application="UnitTests" 
    xmlns="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.rubicon-it.com/Data/DomainObjects/Mapping/1.0 ..\..\..\..\DomainObjects\Schemas\Mapping.xsd">
  <classes>
		<class id="Company">
			<type>Rubicon.Data.DomainObjects.Legacy.UnitTests.TestDomain.Company, Rubicon.Data.DomainObjects.Legacy.UnitTests</type>
			<entity name="Company" />
			<storageProviderID>TestDomain</storageProviderID>
			<properties />
		</class>
		<class id="Customer" baseClass="NonExistingClass">
			<type>Rubicon.Data.DomainObjects.Legacy.UnitTests.TestDomain.Customer, Rubicon.Data.DomainObjects.Legacy.UnitTests</type>
			<entity name="Company" />
			<storageProviderID>TestDomain</storageProviderID>
			<properties />
		</class>
  </classes>
</mapping>
