=== re-motion/Framework-Archive/Web/Core/ExecutionEngine/UrlMapping/UrlMapping.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:m="http://www.rubicon-it.com/Commons/Web/ExecutionEngine/UrlMapping/1.0" 
    elementFormDefault="qualified" 
    attributeFormDefault="unqualified" 
    targetNamespace="http://www.rubicon-it.com/Commons/Web/ExecutionEngine/UrlMapping/1.0" 
    xml:lang="en">

  <!--<xs:import namespace="http://www.rubicon-it.com/Commons/Types" schemaLocation="Types.xsd" />-->

  <xs:element name="urlMapping">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="add" type="m:mappingEntry" maxOccurs="unbounded" />
      </xs:sequence>
	    <xs:attribute name="application" type="m:requiredStringType" use="optional" />
    </xs:complexType>
    
    <xs:key name="resourceKey">
      <xs:selector xpath="m:add" />
      <xs:field xpath="@resource" />
    </xs:key>
    
  </xs:element>

  <xs:complexType name="mappingEntry">
    <xs:attribute name="type" type="m:dotNetType" use="required" />
    <xs:attribute name="resource" type="m:requiredStringType" use="required" />
  </xs:complexType>
  
	<xs:simpleType name="requiredStringType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="dotNetType">
		<xs:restriction base="m:requiredStringType">
			<xs:pattern value=".+,.+" />
		</xs:restriction>				
	</xs:simpleType>

</xs:schema>

=== re-motion/Framework-Archive/SecurityManager/Clients.Web/SecurityManagerUrlMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<urlMapping
    xmlns="http://www.rubicon-it.com/Commons/Web/ExecutionEngine/UrlMapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.rubicon-it.com/Commons/Web/ExecutionEngine/UrlMapping/1.0 UrlMapping.xsd">

  <add type="Rubicon.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.EditTenantFormFunction" resource="EditTenant.wxe" />
  <add type="Rubicon.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.EditGroupFormFunction" resource="EditGroup.wxe" />
  <add type="Rubicon.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.EditUserFormFunction" resource="EditUser.wxe" />
  <add type="Rubicon.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.EditGroupTypeFormFunction" resource="EditGroupType.wxe" />
  <add type="Rubicon.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.EditPositionFormFunction" resource="EditPosition.wxe" />

  <add type="Rubicon.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.TenantListFormFunction" resource="TenantList.wxe" id="TenantList"/>
  <add type="Rubicon.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.GroupListFormFunction" resource="GroupList.wxe" id="GroupList"/>
  <add type="Rubicon.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.UserListFormFunction" resource="UserList.wxe" id="UserList" />
  <add type="Rubicon.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.GroupTypeListFormFunction" resource="GroupTypeList.wxe" id="GroupTypeList"/>
  <add type="Rubicon.SecurityManager.Clients.Web::WxeFunctions.OrganizationalStructure.PositionListFormFunction" resource="PositionList.wxe" id="PositionList"/>

  <add type="Rubicon.SecurityManager.Clients.Web::WxeFunctions.AccessControl.SecurableClassDefinitionListFormFunction" resource="SecurableClassDefinitionList.wxe" id="SecurableClassDefinitionList"/>
</urlMapping>

=== re-motion/Framework-Archive/SecurityManager/Client.Web/SecurityManagerUrlMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<urlMapping
    xmlns="http://www.rubicon-it.com/Commons/Web/ExecutionEngine/UrlMapping/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.rubicon-it.com/Commons/Web/ExecutionEngine/UrlMapping/1.0 UrlMapping.xsd">

  <add type="Rubicon.SecurityManager.Client.Web::WxeFunctions.OrganizationalStructure.EditUserFormFunction" resource="EditUser.wxe" />
  <add type="Rubicon.SecurityManager.Client.Web::WxeFunctions.OrganizationalStructure.UserListFormFunction" resource="UserList.wxe" id="UserList" />
  <add type="Rubicon.SecurityManager.Client.Web::WxeFunctions.OrganizationalStructure.EditGroupTypeFormFunction" resource="EditGroupType.wxe" />
  <add type="Rubicon.SecurityManager.Client.Web::WxeFunctions.OrganizationalStructure.GroupTypeListFormFunction" resource="GroupTypeList.wxe" id="GroupTypeList"/>
  <add type="Rubicon.SecurityManager.Client.Web::WxeFunctions.OrganizationalStructure.EditGroupFormFunction" resource="EditGroup.wxe" />
  <add type="Rubicon.SecurityManager.Client.Web::WxeFunctions.OrganizationalStructure.GroupListFormFunction" resource="GroupList.wxe" id="GroupList"/>
  <add type="Rubicon.SecurityManager.Client.Web::WxeFunctions.OrganizationalStructure.EditPositionFormFunction" resource="EditPosition.wxe" />
  <add type="Rubicon.SecurityManager.Client.Web::WxeFunctions.OrganizationalStructure.PositionListFormFunction" resource="PositionList.wxe" id="PositionList"/>
</urlMapping>
